from __future__ import annotations

import json
from pathlib import Path
from datetime import datetime, timezone
from hashlib import sha256
import importlib.util
import re

ROOT = Path(__file__).resolve().parents[2]
XINGCE = ROOT / 'xingce_v3'
V51_FRONTEND = ROOT / 'v51_frontend'
CONFIG_PATH = Path(__file__).resolve().with_name('legacy_assets_config.py')
_CONFIG_SPEC = importlib.util.spec_from_file_location('legacy_assets_config', CONFIG_PATH)
if _CONFIG_SPEC is None or _CONFIG_SPEC.loader is None:
    raise RuntimeError(f'failed to load legacy assets config: {CONFIG_PATH}')
_CONFIG_MODULE = importlib.util.module_from_spec(_CONFIG_SPEC)
_CONFIG_SPEC.loader.exec_module(_CONFIG_MODULE)
CORE_PARTIALS = _CONFIG_MODULE.CORE_PARTIALS
CSS_SOURCES = _CONFIG_MODULE.CSS_SOURCES
JS_SOURCES = _CONFIG_MODULE.JS_SOURCES
JS_VIEW_SPLIT_SOURCES = _CONFIG_MODULE.JS_VIEW_SPLIT_SOURCES
VIEW_BUNDLE_SIZE_WARNINGS = getattr(_CONFIG_MODULE, 'VIEW_BUNDLE_SIZE_WARNINGS', {})
DUPLICATE_FUNCTION_NAME_ALLOWLIST = set(getattr(_CONFIG_MODULE, 'DUPLICATE_FUNCTION_NAME_ALLOWLIST', set()))
DUPLICATE_FUNCTION_SCAN_PREFIXES = tuple(getattr(_CONFIG_MODULE, 'DUPLICATE_FUNCTION_SCAN_PREFIXES', ('modules/main/',)))


def load_v51_partials_manifest() -> list[str]:
    manifest_path = V51_FRONTEND / 'partials-manifest.json'
    return json.loads(manifest_path.read_text(encoding='utf-8'))


def build_partials_bundle(partials: list[str]) -> str:
    chunks = []
    for name in partials:
        source_path = V51_FRONTEND / 'partials' / name
        if not source_path.exists():
            raise FileNotFoundError(source_path)
        chunks.append(source_path.read_text(encoding='utf-8').rstrip())
    return '\n'.join(chunks) + '\n'


def bundle_contents(paths: list[str], comment_prefix: str) -> str:
    built_at = datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%SZ')
    chunks = [f'/* Generated by scripts/build_legacy_assets.py at {built_at} */\n']
    for rel in paths:
        source_path = XINGCE / rel
        if not source_path.exists():
            raise FileNotFoundError(source_path)
        content = source_path.read_text(encoding='utf-8')
        chunks.append(f'\n{comment_prefix} BEGIN: {rel} */\n')
        chunks.append(content.rstrip())
        chunks.append(f'\n{comment_prefix} END: {rel} */\n')
    return ''.join(chunks) + '\n'


def file_sha256(path: Path) -> str:
    digest = sha256()
    digest.update(path.read_bytes())
    return digest.hexdigest()


def build_manifest(css_bundle_path: Path, js_bundle_path: Path, view_bundle_paths: dict[str, Path]) -> dict[str, object]:
    manifest = {
        'built_at': datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ'),
        'css_bundle': {
            'path': str(css_bundle_path.relative_to(ROOT)),
            'sha256': file_sha256(css_bundle_path),
            'sources': CSS_SOURCES,
        },
        'js_bundle': {
            'path': str(js_bundle_path.relative_to(ROOT)),
            'sha256': file_sha256(js_bundle_path),
            'sources': JS_SOURCES,
        },
    }
    manifest['js_view_bundles'] = {
        name: {
            'path': str(path.relative_to(ROOT)),
            'sha256': file_sha256(path),
            'sources': JS_VIEW_SPLIT_SOURCES[name],
        }
        for name, path in view_bundle_paths.items()
    }
    return manifest


_FUNC_DECL_RE = re.compile(r'^\s*function\s+([A-Za-z_$][A-Za-z0-9_$]*)\s*\(', re.MULTILINE)
_FUNC_EXPR_RE = re.compile(r'^\s*(?:const|let|var)\s+([A-Za-z_$][A-Za-z0-9_$]*)\s*=\s*function\b', re.MULTILINE)


def collect_duplicate_function_names(js_sources: list[str]) -> dict[str, set[str]]:
    name_to_files: dict[str, set[str]] = {}
    for rel in js_sources:
        if not rel.endswith('.js'):
            continue
        if DUPLICATE_FUNCTION_SCAN_PREFIXES and not rel.startswith(DUPLICATE_FUNCTION_SCAN_PREFIXES):
            continue
        source_path = XINGCE / rel
        if not source_path.exists():
            continue
        text = source_path.read_text(encoding='utf-8')
        names = set(_FUNC_DECL_RE.findall(text)) | set(_FUNC_EXPR_RE.findall(text))
        for name in names:
            if name in DUPLICATE_FUNCTION_NAME_ALLOWLIST:
                continue
            name_to_files.setdefault(name, set()).add(rel)
    return {name: files for name, files in name_to_files.items() if len(files) > 1}


def report_split_bundle_size_warnings(view_bundle_paths: dict[str, Path]) -> list[str]:
    warnings: list[str] = []
    for view_name, threshold in VIEW_BUNDLE_SIZE_WARNINGS.items():
        bundle_path = view_bundle_paths.get(view_name)
        if not bundle_path or not bundle_path.exists():
            continue
        size = bundle_path.stat().st_size
        if size > int(threshold):
            warnings.append(
                f'[{view_name}] {size} B > warn threshold {int(threshold)} B'
            )
    return warnings


def report_duplicate_function_warnings() -> list[str]:
    duplicates = collect_duplicate_function_names(JS_SOURCES)
    lines: list[str] = []
    for name in sorted(duplicates.keys()):
        files = ', '.join(sorted(duplicates[name]))
        lines.append(f'[{name}] defined in: {files}')
    return lines


def main() -> None:
    css_bundle_path = XINGCE / 'styles' / 'legacy-app.bundle.css'
    js_bundle_path = XINGCE / 'modules' / 'legacy-app.bundle.js'
    manifest_path = XINGCE / 'legacy-app.bundle.manifest.json'
    view_bundle_paths = {
        name: XINGCE / 'modules' / f'legacy-app.{name}.bundle.js'
        for name in JS_VIEW_SPLIT_SOURCES.keys()
    }
    partials_bundle_path = V51_FRONTEND / 'partials.bundle.html'
    deferred_partials_bundle_path = V51_FRONTEND / 'deferred-partials.bundle.html'
    partials_manifest = load_v51_partials_manifest()
    deferred_partials = [name for name in partials_manifest if name not in CORE_PARTIALS]

    css_bundle_path.write_text(bundle_contents(CSS_SOURCES, '/*'), encoding='utf-8')
    js_bundle_path.write_text(bundle_contents(JS_SOURCES, '/*'), encoding='utf-8')
    for name, source_list in JS_VIEW_SPLIT_SOURCES.items():
        view_bundle_paths[name].write_text(bundle_contents(source_list, '/*'), encoding='utf-8')
    partials_bundle_path.write_text(build_partials_bundle(CORE_PARTIALS), encoding='utf-8')
    deferred_partials_bundle_path.write_text(build_partials_bundle(deferred_partials), encoding='utf-8')
    manifest_path.write_text(json.dumps(build_manifest(css_bundle_path, js_bundle_path, view_bundle_paths), ensure_ascii=False, indent=2) + '\n', encoding='utf-8')

    duplicate_warnings = report_duplicate_function_warnings()
    size_warnings = report_split_bundle_size_warnings(view_bundle_paths)

    print(f'Wrote {css_bundle_path.relative_to(ROOT)}')
    print(f'Wrote {js_bundle_path.relative_to(ROOT)}')
    for name, path in view_bundle_paths.items():
        print(f'Wrote {path.relative_to(ROOT)}')
    print(f'Wrote {partials_bundle_path.relative_to(ROOT)}')
    print(f'Wrote {deferred_partials_bundle_path.relative_to(ROOT)}')
    print(f'Wrote {manifest_path.relative_to(ROOT)}')
    if duplicate_warnings:
        print('WARN duplicate function names detected:')
        for line in duplicate_warnings:
            print(f'  - {line}')
    if size_warnings:
        print('WARN split bundle size threshold exceeded:')
        for line in size_warnings:
            print(f'  - {line}')


if __name__ == '__main__':
    main()
